export type Product = {
  id: string;
  sku: string;
  name: string;
  shortDesc: string;
  fullDesc: string;
  price: number;
  slug: string;
  category: "Branding" | "Web Design" | "Marketing" | "Strategy" | "Content Marketing" | "SEO Strategy" | "Advertising" | "Email Marketing" | "Design Services" | "Consulting";
};

export const products: Product[] = [
  { id: "1", sku: "KCA-BRN-001", name: "Brand Identity Sprint", shortDesc: "Complete logo and brand guideline package.", fullDesc: "A 2-week intensive sprint to redefine your brand. Includes primary/secondary logo design, color palette, typography selection, and a comprehensive 20-page PDF Brand Guideline document to ensure consistency across all your marketing channels.", price: 2500, category: "Branding", slug: "brand-identity-sprint" },
  { id: "2", sku: "KCA-SOC-002", name: "Social Media Starter Kit", shortDesc: "15 custom-designed social media templates.", fullDesc: "Stop stressing over what to post. We provide 15 fully editable Canva or Figma templates customized to your brand, including feed posts, carousel layouts, and story graphics. Designed for maximum engagement on IG and LinkedIn.", price: 450, category: "Design Services", slug: "social-media-starter-kit" },
  { id: "3", sku: "KCA-CNT-003", name: "Monthly Content Retainer", shortDesc: "12 SEO blog posts and 1 newsletter per month.", fullDesc: "Fuel your inbound marketing engine. Our expert copywriters will deliver 12 SEO-optimized blog articles (800+ words each) and draft one engaging monthly email newsletter to keep your audience converting.", price: 1800, category: "Content Marketing", slug: "monthly-content-retainer" },
  { id: "4", sku: "KCA-WEB-004", name: "Custom Landing Page", shortDesc: "High-converting standalone landing page.", fullDesc: "Launching a new product or ad campaign? We will design and develop a single, highly optimized landing page focused entirely on conversion. Includes copywriting, custom graphics, and CRM lead capture integration.", price: 1200, category: "Web Design", slug: "custom-landing-page" },
  { id: "5", sku: "KCA-SEO-005", name: "SEO Site Audit & Strategy", shortDesc: "Comprehensive technical and on-page SEO audit.", fullDesc: "Find out exactly why you aren't ranking. We run a deep-dive audit of your site's technical health, backlink profile, and content. You receive a detailed video walkthrough and a prioritized 90-day execution roadmap.", price: 850, category: "SEO Strategy", slug: "seo-site-audit-strategy" },
  { id: "6", sku: "KCA-WEB-006", name: "E-Commerce Web Build", shortDesc: "Custom Shopify or WooCommerce setup.", fullDesc: "A complete, end-to-end e-commerce website design and build. Includes custom theme styling, up to 50 product uploads, payment gateway integration, and essential sales-driving plugins. Handover includes a 1-hour training call.", price: 4500, category: "Web Design", slug: "ecommerce-web-build" },
  { id: "7", sku: "KCA-ADS-007", name: "Ad Creative Bundle", shortDesc: "10 static and 2 video assets for paid ads.", fullDesc: "Stop scrolling and start selling. Our design team will create high-performing, thumb-stopping ad creatives tailored for Facebook, Instagram, or TikTok. Includes A/B testing variations and persuasive ad copy.", price: 950, category: "Advertising", slug: "ad-creative-bundle" },
  { id: "8", sku: "KCA-STR-008", name: "Marketing Strategy Blueprint", shortDesc: "6-month custom digital marketing roadmap.", fullDesc: "A foundational strategy for growth. We analyze your competitors, define your buyer personas, and map out a step-by-step, 6-month digital marketing plan covering organic, paid, and email channels.", price: 1500, category: "Strategy", slug: "marketing-strategy-blueprint" },
  { id: "9", sku: "KCA-EML-009", name: "Email Automation Setup", shortDesc: "Welcome sequence and abandoned cart flows.", fullDesc: "Maximize your customer lifetime value. We will map out, write, and implement a 5-email Welcome Sequence and a 3-email Abandoned Cart flow in Klaviyo or Mailchimp to drive sales on autopilot.", price: 700, category: "Email Marketing", slug: "email-automation-setup" },
  { id: "10", sku: "KCA-BRN-010", name: "Pitch Deck Design", shortDesc: "15-slide investor presentation design.", fullDesc: "Make a lasting impression on investors or enterprise clients. We take your raw data and transform it into a visually stunning, persuasive 15-slide pitch deck that tells your brand's story effectively.", price: 1100, category: "Design Services", slug: "pitch-deck-design" },
  { id: "11", sku: "KCA-CNS-011", name: "1-on-1 Marketing Power Hour", shortDesc: "60-minute strategic consultation call.", fullDesc: "Pick the brain of a senior marketing director. Bring your biggest bottlenecks, campaign ideas, or data, and we will spend 60 minutes solving problems and providing actionable next steps. Includes a call recording.", price: 250, category: "Consulting", slug: "marketing-power-hour" },
  { id: "12", sku: "KCA-WEB-012", name: "Website Performance Overhaul", shortDesc: "Speed and UX optimization for existing sites.", fullDesc: "Slow sites kill conversions. We audit your existing WordPress website, compress media, minify code, improve caching, and fix critical UX errors to boost your Google PageSpeed scores and lower bounce rates.", price: 600, category: "Web Design", slug: "website-performance-overhaul" },
];